# Generated by Django 5.0.6 on 2024-08-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_batch_batch_status'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'semester')},
        ),
    ]
