# Generated by Django 5.0.6 on 2024-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Semester Drop', 'Semester Drop'), ('Dropout', 'Dropout'), ('Pass Out', 'Pass Out')], max_length=50),
        ),
    ]
