# Generated by Django 5.0.6 on 2024-07-28 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_name', models.CharField(max_length=100)),
                ('record_year', models.IntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='academics.batch')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='academics.program')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamRecord',
            fields=[
                ('student_exam_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('internal_marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mid_marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage_per_course', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa_per_course', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_records', to='academics.course')),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_records', to='records.examrecord')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_records', to='academics.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_records', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_records', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSemesterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_semester_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester_obtained_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa_per_semester', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Probation', 'Probation'), ('Semester Drop', 'Semester Drop'), ('Dropout', 'Dropout'), ('Pass Out', 'Pass Out')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_records', to='students.student')),
                ('student_exam_rec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='semester_record', to='records.studentexamrecord')),
            ],
        ),
    ]
