# Generated by Django 5.0.6 on 2024-07-31 12:08

import datetime
import django.db.models.deletion
import records.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('records', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamrecord',
            unique_together={('exam_record', 'student', 'course')},
        ),
        migrations.AddField(
            model_name='examrecord',
            name='exam_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='studentexamrecord',
            name='final_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[records.models.validate_percentage]),
        ),
        migrations.AddField(
            model_name='studentexamrecord',
            name='internal_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[records.models.validate_percentage]),
        ),
        migrations.AddField(
            model_name='studentexamrecord',
            name='mid_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[records.models.validate_percentage]),
        ),
        migrations.AddField(
            model_name='studentsemesterrecord',
            name='exam_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.examrecord'),
        ),
        migrations.AddField(
            model_name='studentsemesterrecord',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.batch'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='examiner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='record_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='exam_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.examrecord'),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='gpa_per_course',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[records.models.validate_gpa]),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='percentage_per_course',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[records.models.validate_percentage]),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.program'),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[records.models.validate_gpa]),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='gpa_per_semester',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[records.models.validate_gpa]),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[records.models.validate_percentage]),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='semester_obtained_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[records.models.validate_percentage]),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='student_exam_rec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.studentexamrecord'),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='total_semester_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[records.models.validate_percentage]),
        ),
        migrations.AlterUniqueTogether(
            name='examrecord',
            unique_together={('record_name', 'record_year', 'exam_date')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsemesterrecord',
            unique_together={('student', 'semester', 'exam_record')},
        ),
        migrations.RemoveField(
            model_name='studentexamrecord',
            name='final_marks_obtained',
        ),
        migrations.RemoveField(
            model_name='studentexamrecord',
            name='internal_marks_obtained',
        ),
        migrations.RemoveField(
            model_name='studentexamrecord',
            name='mid_marks_obtained',
        ),
    ]
