# Generated by Django 5.0.6 on 2024-07-31 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('records', '0003_alter_studentexamrecord_final_marks_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrecord',
            name='exam_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='exam_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.examrecord'),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program'),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='exam_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.examrecord'),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='student_exam_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.studentexamrecord'),
        ),
    ]
