# Generated by Django 5.0.6 on 2024-08-04 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_batch_batch_status'),
        ('records', '0005_rename_status_studentsemesterrecord_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.batch')),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.examrecord')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
            ],
        ),
    ]
