# Generated by Django 5.0.6 on 2024-08-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_batch_batch_status'),
        ('records', '0006_examenrollment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examenrollment',
            unique_together={('exam_record', 'batch', 'semester')},
        ),
    ]
