# Generated by Django 5.0.6 on 2024-08-05 13:31

import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_examenrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamrecord',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[records.models.validate_percentage]),
            preserve_default=False,
        ),
    ]
