# Generated by Django 5.0.6 on 2024-08-06 11:20

import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_studentexamrecord_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamrecord',
            name='percentage_per_course',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[records.models.validate_percentage]),
        ),
    ]
