# Generated by Django 5.0.6 on 2024-08-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_studentexamrecord_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamrecord',
            name='percentage_per_course',
        ),
    ]
