# Generated by Django 5.0.6 on 2024-08-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_session',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_session_end',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_session_start',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
