# Generated by Django 5.0.6 on 2024-08-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_batch_batch_session_batch_batch_session_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_session_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_session_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(max_length=50),
        ),
    ]
