# Generated by Django 5.0.6 on 2024-08-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_batch_batch_session_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
